DEMO_ITEMS = [
    {
        "title": "Nike Shox TL Silver",
        "brand": "Nike",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Обувь",
        "size": "EU 42",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 8200,
        "shipping_price": 2800,
        "total_price_rub": 11000,
        "avito_price": 16500,
        "expected_profit": 5500,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "New Balance 2002R Protection Pack",
        "brand": "New Balance",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Обувь",
        "size": "EU 43",
        "image_url": "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 9400,
        "shipping_price": 3000,
        "total_price_rub": 12400,
        "avito_price": 18900,
        "expected_profit": 6500,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Arc'teryx Beta Jacket",
        "brand": "Arc'teryx",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Верх",
        "size": "M",
        "image_url": "https://images.unsplash.com/photo-1548883354-94bcfe321cbb?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 22500,
        "shipping_price": 4300,
        "total_price_rub": 26800,
        "avito_price": 36500,
        "expected_profit": 9700,
        "risk_level": "high",
        "seller_is_suspicious": False,
        "authenticity_risk": "high",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Stussy Work Pants",
        "brand": "Stussy",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Низ",
        "size": "L",
        "image_url": "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 4700,
        "shipping_price": 2200,
        "total_price_rub": 6900,
        "avito_price": 10900,
        "expected_profit": 4000,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Supreme Waist Bag",
        "brand": "Supreme",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Аксессуары",
        "size": "One size",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 6500,
        "shipping_price": 1900,
        "total_price_rub": 8400,
        "avito_price": 13200,
        "expected_profit": 4800,
        "risk_level": "high",
        "seller_is_suspicious": True,
        "authenticity_risk": "high",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Asics Gel-Kayano 14 Cream",
        "brand": "Asics",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Обувь",
        "size": "EU 41",
        "image_url": "https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 7600,
        "shipping_price": 2700,
        "total_price_rub": 10300,
        "avito_price": 14900,
        "expected_profit": 4600,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Nike ACG Fleece",
        "brand": "Nike",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Верх",
        "size": "XL",
        "image_url": "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 5200,
        "shipping_price": 2400,
        "total_price_rub": 7600,
        "avito_price": 11900,
        "expected_profit": 4300,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Carhartt Cargo Pants",
        "brand": "Carhartt",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Низ",
        "size": "W32",
        "image_url": "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 3900,
        "shipping_price": 2100,
        "total_price_rub": 6000,
        "avito_price": 9800,
        "expected_profit": 3800,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Chrome Hearts Cap",
        "brand": "Chrome Hearts",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Аксессуары",
        "size": "One size",
        "image_url": "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 7200,
        "shipping_price": 1600,
        "total_price_rub": 8800,
        "avito_price": 16500,
        "expected_profit": 7700,
        "risk_level": "high",
        "seller_is_suspicious": True,
        "authenticity_risk": "high",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Adidas Samba OG",
        "brand": "Adidas",
        "country": "Китай",
        "platform": "Goofish",
        "category": "Обувь",
        "size": "EU 40",
        "image_url": "https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 6100,
        "shipping_price": 2600,
        "total_price_rub": 8700,
        "avito_price": 12900,
        "expected_profit": 4200,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://www.goofish.com/",
    },
    {
        "title": "Porter Tanker Shoulder Bag",
        "brand": "Porter",
        "country": "Япония",
        "platform": "Mercari",
        "category": "Аксессуары",
        "size": "S",
        "image_url": "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 6100,
        "shipping_price": 3200,
        "total_price_rub": 9300,
        "avito_price": 13900,
        "expected_profit": 4600,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://jp.mercari.com/",
    },
    {
        "title": "Comme des Garcons Shirt",
        "brand": "Comme des Garcons",
        "country": "Япония",
        "platform": "Mercari",
        "category": "Верх",
        "size": "M",
        "image_url": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 5400,
        "shipping_price": 2900,
        "total_price_rub": 8300,
        "avito_price": 12800,
        "expected_profit": 4500,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://jp.mercari.com/",
    },
    {
        "title": "Yohji Yamamoto Wool Pants",
        "brand": "Yohji Yamamoto",
        "country": "Япония",
        "platform": "Yahoo Auctions",
        "category": "Низ",
        "size": "M",
        "image_url": "https://images.unsplash.com/photo-1594633313593-bab3825d0caf?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 12500,
        "shipping_price": 3900,
        "total_price_rub": 16400,
        "avito_price": 24500,
        "expected_profit": 8100,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://auctions.yahoo.co.jp/",
    },
    {
        "title": "Issey Miyake Pleats Top",
        "brand": "Issey Miyake",
        "country": "Япония",
        "platform": "Mercari",
        "category": "Верх",
        "size": "L",
        "image_url": "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 9800,
        "shipping_price": 3500,
        "total_price_rub": 13300,
        "avito_price": 21000,
        "expected_profit": 7700,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://jp.mercari.com/",
    },
    {
        "title": "Needles Track Pants",
        "brand": "Needles",
        "country": "Япония",
        "platform": "Mercari",
        "category": "Низ",
        "size": "S",
        "image_url": "https://images.unsplash.com/photo-1506629905607-d405d7d3b0d2?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 8700,
        "shipping_price": 3100,
        "total_price_rub": 11800,
        "avito_price": 17200,
        "expected_profit": 5400,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://jp.mercari.com/",
    },
    {
        "title": "Visvim FBT",
        "brand": "Visvim",
        "country": "Япония",
        "platform": "Yahoo Auctions",
        "category": "Обувь",
        "size": "US 9",
        "image_url": "https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 21000,
        "shipping_price": 4300,
        "total_price_rub": 25300,
        "avito_price": 37500,
        "expected_profit": 12200,
        "risk_level": "high",
        "seller_is_suspicious": False,
        "authenticity_risk": "high",
        "source_url": "https://auctions.yahoo.co.jp/",
    },
    {
        "title": "Bape Shark Hoodie",
        "brand": "Bape",
        "country": "Япония",
        "platform": "Mercari",
        "category": "Верх",
        "size": "M",
        "image_url": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 13500,
        "shipping_price": 3600,
        "total_price_rub": 17100,
        "avito_price": 26000,
        "expected_profit": 8900,
        "risk_level": "high",
        "seller_is_suspicious": True,
        "authenticity_risk": "high",
        "source_url": "https://jp.mercari.com/",
    },
    {
        "title": "Kapital Bandana Jacket",
        "brand": "Kapital",
        "country": "Япония",
        "platform": "Yahoo Auctions",
        "category": "Верх",
        "size": "L",
        "image_url": "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 28500,
        "shipping_price": 5200,
        "total_price_rub": 33700,
        "avito_price": 46800,
        "expected_profit": 13100,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://auctions.yahoo.co.jp/",
    },
    {
        "title": "Hysteric Glamour Denim",
        "brand": "Hysteric Glamour",
        "country": "Япония",
        "platform": "Mercari",
        "category": "Низ",
        "size": "W30",
        "image_url": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 7900,
        "shipping_price": 3100,
        "total_price_rub": 11000,
        "avito_price": 16800,
        "expected_profit": 5800,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://jp.mercari.com/",
    },
    {
        "title": "Seiko 5 Sports Watch",
        "brand": "Seiko",
        "country": "Япония",
        "platform": "Yahoo Auctions",
        "category": "Аксессуары",
        "size": "42 mm",
        "image_url": "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 11200,
        "shipping_price": 2600,
        "total_price_rub": 13800,
        "avito_price": 19900,
        "expected_profit": 6100,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://auctions.yahoo.co.jp/",
    },
    {
        "title": "Carhartt Detroit Jacket",
        "brand": "Carhartt",
        "country": "США",
        "platform": "eBay",
        "category": "Верх",
        "size": "L",
        "image_url": "https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 11800,
        "shipping_price": 5200,
        "total_price_rub": 17000,
        "avito_price": 26500,
        "expected_profit": 9500,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://www.ebay.com/",
    },
    {
        "title": "Levi's 501 Made in USA",
        "brand": "Levi's",
        "country": "США",
        "platform": "Depop",
        "category": "Низ",
        "size": "W32",
        "image_url": "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 4900,
        "shipping_price": 4100,
        "total_price_rub": 9000,
        "avito_price": 14500,
        "expected_profit": 5500,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://www.depop.com/",
    },
    {
        "title": "Nike ACG Mountain Fly",
        "brand": "Nike",
        "country": "США",
        "platform": "Mercari US",
        "category": "Обувь",
        "size": "US 10",
        "image_url": "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 9700,
        "shipping_price": 4800,
        "total_price_rub": 14500,
        "avito_price": 21900,
        "expected_profit": 7400,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://www.mercari.com/",
    },
    {
        "title": "Chrome Hearts Trucker Cap",
        "brand": "Chrome Hearts",
        "country": "США",
        "platform": "eBay",
        "category": "Аксессуары",
        "size": "One size",
        "image_url": "https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 15500,
        "shipping_price": 4300,
        "total_price_rub": 19800,
        "avito_price": 34500,
        "expected_profit": 14700,
        "risk_level": "high",
        "seller_is_suspicious": True,
        "authenticity_risk": "high",
        "source_url": "https://www.ebay.com/",
    },
    {
        "title": "Patagonia Synchilla Fleece",
        "brand": "Patagonia",
        "country": "США",
        "platform": "Depop",
        "category": "Верх",
        "size": "M",
        "image_url": "https://images.unsplash.com/photo-1539533113208-f6df8cc8b543?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 6200,
        "shipping_price": 4300,
        "total_price_rub": 10500,
        "avito_price": 16900,
        "expected_profit": 6400,
        "risk_level": "low",
        "seller_is_suspicious": False,
        "authenticity_risk": "low",
        "source_url": "https://www.depop.com/",
    },
    {
        "title": "Oakley Archive Sunglasses",
        "brand": "Oakley",
        "country": "США",
        "platform": "Mercari US",
        "category": "Аксессуары",
        "size": "One size",
        "image_url": "https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=900&q=80",
        "purchase_price": 7300,
        "shipping_price": 3900,
        "total_price_rub": 11200,
        "avito_price": 17800,
        "expected_profit": 6600,
        "risk_level": "medium",
        "seller_is_suspicious": False,
        "authenticity_risk": "medium",
        "source_url": "https://www.mercari.com/",
    },
]
